#!/bin/sh
#
# $Id: plotdemodetector,v 1.3 2006/05/01 22:25:57 tjohnson Exp $
#
# This script takes a standard out log file from the demo detector on the root node,
# and plots a + for each message which did not arrive.  X is node address,
# Y is message sequence number.

#node 192.168.1.116 report 1 distance 1



awk ' $1 == "node" && $3 == "report" { print $2 " " $4 } ' $* | awk ' BEGIN { FS="[. ]"} { print $4 " " $5 } ' | awk ' BEGIN { minnode=255; maxnode=0 ; maxmsg=0 ; minmsg=-1 } $1-0 < minnode { minnode=$1-0 } $1-0 > maxnode {maxnode=$1-0} $2>maxmsg { maxmsg=$2 } (minmsg < 0) || ($2 < minmsg) { minmsg=$2} { packet[$1-0,$2]=1; } END { for(node=minnode;node<=maxnode;node++) { for(msg=minmsg;msg<maxmsg;msg++) { tot++ ; if (packet[node,msg]==0) { print node " " msg ; missing++ } } } ; print "total: " tot " missing: " missing " percent: " missing/tot > "final" } ' > testtraffic

cat <<EOF | gnuplot
set title "Hierarchy Connectivity"
set key
set terminal postscript color
set output "demodetector.ps"
plot "testtraffic"
EOF

cat final

