#!/bin/sh
#
# $Id: runhslsd,v 1.5 2006/11/13 16:06:35 tjohnson Exp $
#
# Script to run hslsd from data in a simulator config file
# intended to be called by runcoke

PATH=$PATH:/sbin:/usr/sbin
export PATH

CONFFILE=$1

TAG=349854

if test x$CONFFILE = x
then
echo "usage: runhslsd configfile"
exit
fi

labeltest -g $TAG -n 0 -r gn

manetnetwork=`awk ' BEGIN {FS=":"} $1=="manetnetwork" {  split($2,addr,"[:.]") ; print addr[1] "." addr[2] "." addr[3]  } ' $CONFFILE `

tmp=`/sbin/ifconfig -a | awk ' $2=="Link" { interface= $1 } $1=="inet" { if (index($2,"'$manetnetwork'")==6) print interface " " $2 } '`

interface=`echo $tmp | awk ' { print $1 } ' `
addr=`echo $tmp | awk ' { print $2 } ' | awk ' BEGIN { FS=":" } { print $2 } ' `

echo "manet $manetnetwork interface $interface addr $addr"
echo

# Nuke any existing routes...
#netstat -rn | awk ' $1 ~ /'$manetnetwork'.*/ { print "/sbin/route del -host " $1 " gw " $2  } ' | sh
ip route flush scope global type unicast;

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 > /proc/sys/net/ipv4/conf/$interface/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/$interface/accept_redirects
echo 0 > /proc/sys/net/ipv4/conf/default/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/default/accept_redirects
echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects

#/sbin/route add -net 224.0.0.0/4 dev $interface

ulimit -c unlimited

#./hslsd -d -f inet -i $interface -m -L all
#./hslsd -d -f inet -i $interface -m -a $addr/24 -L all
./hslsd -d  -f inet -t ptmp -i $interface -m -L all

./labeltest -g $TAG -b 255.0.0.255 -f 255.255.255.255 -l "hslsd crashed"
