#!/bin/sh
#
# script to walk the list of result files, and display their elapsed times
#
# $Id: checktimes,v 1.2 2005/01/20 00:41:32 tjohnson Exp $
#
for i in *res/foo
do
echo -n "$i "
tail -1000 $i | grep "^time:" | tail -1
done 

