#!/bin/sh
#
# $Id: plottesttraffic,v 1.3 2005/01/07 18:54:19 tjohnson Exp $
#

name=`pwd`
numnodes=` basename $name | awk ' BEGIN { FS="\."} { print substr($1,6) } ' `

# node 6: testtraffic data, time= 10002 got a packet src= 9 dst= 6 testid= 0


# grep "testtraffic data"  $* | awk ' $6 != "nan" { print $11 " " $13 " " $15 } ' > testtraffic

grep "testtraffic data"  $* | awk ' { print $11 " " $13 " " $15 } ' | awk ' { packet[$1,$2,$3]=1; } END { for(seq=0;flag==0;seq++) { flag=1 ; for(src=101;src<111;src++) { for(dst=101;dst<111;dst++) { if (packet[src,dst,seq]>0) { flag=0} ; if (packet[src,dst,seq]==0) { print src " " dst " " seq } }}}} ' > testtraffic


exit

cat <<EOF | gnuplot
set title "Testtraffic Connectivity"
set key
set terminal postscript color
set output "floodtest.ps"
splot "testtraffic"
EOF



