#!/bin/sh
#
# This script takes a wnte file, and converts it
# into a locations file, as groked by the simulator
#
# $Id: wnte2location,v 1.4 2005/10/07 17:06:47 tjohnson Exp $
#

awk ' BEGIN {num=0; maxy=0} { addr[num]=$2 ; x[num]=$3; y[num]=$4 ; num++ } $4 > maxy { maxy=$4} END { for(i=0;i<num;i++) { print addr[i] " at " x[i] " " maxy-y[i] } } ' $*
