# Common definitions for client apps
# included in every client Makefile.in

include $(top_srcdir)/Makefile.top

CPPFLAGS += -I$(top_srcdir)/clients/include

LDADD = $(top_srcdir)/libwatcher/libwatchermsg.la 
LDADD += $(top_srcdir)/libwatcher/libwatcher.a 
LDADD += $(top_srcdir)/util/libwatcherutils.a 
