#!/bin/sh
#
# Init file for Watcher Daemon
#
# chkconfig: - 80 20
# description: Watcher Daemon
# processname: watcherd
# config: /etc/sysconfig/watcherd
# pidfile: /var/run/watcherd.pid
#

# Source function library.
. /etc/init.d/functions

prog="watcherd"
[ -f /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start()
{
}

stop()
{
}

reload()
{
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $prog
        ;;
  restart|reload)
        stop
        start
        ;;
  condrestart)
        if [ -f /var/lock/subsys/$prog ]; then
                stop
                start -w
        fi
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
        exit 1
esac

exit $?
