# This file gets included in every Makefile.in

# "Fixes" warning in log4cxx about type punning. 
CPPFLAGS += -fno-strict-aliasing

CPPFLAGS += -O2

# "Fixes" warning about old headers
CPPFLAGS += -Wno-deprecated

CPPFLAGS += -I$(top_srcdir)
CPPFLAGS += -I$(top_srcdir)/util
CPPFLAGS += $(BOOST_CPPFLAGS) @LOGGER_CFLAGS@

# root of the watcher tree, one directory up from the srcdir
TOPDIR=$(top_srcdir)/..

LIBS += -lconfig++
LIBS += -llog4cxx
LIBS += $(BOOST_ASIO_LIB) $(BOOST_SERIALIZATION_LIB) $(BOOST_THREAD_LIB) $(BOOST_SYSTEM_LIB) $(BOOST_FILESYSTEM_LIB) $(BOOST_REGEX_LIB)
LIBS += $(LOGGER_LIBS)

LDFLAGS += $(BOOST_LDFLAGS)

#
# Copy sample cfg and log.properties files from ../etc
#
%.cfg : 
	@ echo Creating $*.cfg from sample configuration at $(TOPDIR)/etc/$*.cfg.sample
	cp -v $(TOPDIR)/etc/$*.cfg.sample ./$*.cfg

%.log.properties: 
	@ echo Creating $*.log.properties from sample configuration at $(TOPDIR)/etc/watcher.log.properties.sample
	cp -v $(TOPDIR)/etc/watcherd.log.properties.sample ./$*.log.properties
	@ echo This is probably a bad idea - attempting to set the correct output log file in log.properties.
	@ perl -pi -e 's/watcherd.log/$*.log/g' ./$*.log.properties

ctags:
	ctags -R $(TOPDIR)

# make install into staging dir, uninstall "server" components by hand, 
# then tar it up and remove the tmp dir.
TMPDISTDIR = $(shell pwd)/tmpDistDir
testnode-dist:
	@echo Temporarily installing distribution
	mkdir -p $(TMPDISTDIR) && $(MAKE) DESTDIR=$(TMPDISTDIR) install
	@echo Removing non-testnode files from distribution
	$(RM) $(TMPDISTDIR)/$(bindir)/showClock
	$(RM) $(TMPDISTDIR)/$(bindir)/messageStream2Text
	$(RM) $(TMPDISTDIR)/$(bindir)/connectivity2dot
	$(RM) $(TMPDISTDIR)/$(bindir)/watcherd
	@echo Creating $(top_srcdir)/testnode-dist.tbz tar file.
	tar jcvf $(top_srcdir)/testnode-dist.tbz -C $(TMPDISTDIR) .
	@echo Removing tmp installation directory
	$(RM) -r $(TMPDISTDIR)
	@echo testnode-dist complete, testnode-dist is $(top_srcdir)/testnode-dist.tbz

# make install into staging dir, uninstall "testnode" components by hand, 
# then tar it up and remove the tmp dir.
testnode-dist:
	@echo Temporarily installing distribution
	mkdir -p $(TMPDISTDIR) && $(MAKE) DESTDIR=$(TMPDISTDIR) install
	@echo Removing non-servernode files from distribution
	$(RM) $(TMPDISTDIR)/$(bindir)/routeFeeder
	@echo Creating $(top_srcdir)/testnode-dist.tbz tar file.
	tar jcvf $(top_srcdir)/testnode-dist.tbz -C $(TMPDISTDIR) .
	@echo Removing tmp installation directory
	$(RM) -r $(TMPDISTDIR)
	@echo testnode-dist complete, testnode-dist is $(top_srcdir)/testnode-dist.tbz

