# This file gets included in every Makefile.in

# "Fixes" warning in log4cxx about type punning. 
CPPFLAGS += -fno-strict-aliasing

CPPFLAGS += -I$(top_srcdir)
CPPFLAGS += -I$(top_srcdir)/util
CPPFLAGS += -I$(top_srcdir)/logger
CPPFLAGS += $(BOOST_CPPFLAGS)

TOPDIR=$(top_srcdir)/../etc

LIBS += -lconfig++
LIBS += -llog4cxx
LIBS += $(BOOST_ASIO_LIB) $(BOOST_SERIALIZATION_LIB) $(BOOST_THREAD_LIB) $(BOOST_SYSTEM_LIB) $(BOOST_FILESYSTEM_LIB) $(BOOST_REGEX_LIB)

LDFLAGS += $(BOOST_LDFLAGS)

#
# Copy sample cfg and log.properties files from ../etc
#
%.cfg : 
	@ echo Creating $*.cfg from sample configuration at $(TOPDIR)/etc/$*.cfg.sample
	cp -v $(TOPDIR)/etc/$*.cfg.sample ./$*.cfg

%.log.properties: 
	@ echo Creating $*.log.properties from sample configuration at $(TOPDIR)/etc/watcher.log.properties.sample
	cp -v $(TOPDIR)/etc/watcherd.log.properties.sample ./$*.log.properties
	@ echo This is probably a bad idea - attempting to set the correct output log file in log.properties.
	@ perl -pi -e 's/watcherd.log/$*.log/g' ./$*.log.properties

ctags:
	ctags -R $(TOPDIR)
