# This file gets included in every Makefile.in

CPPFLAGS = -DDATADIR='"$(datadir)"'  -DSYSCONFDIR='"$(sysconfdir)"' @CPPFLAGS@

# "Fixes" warning in log4cxx about type punning. 
CPPFLAGS += -fno-strict-aliasing
# CPPFLAGS += -O3
# CXXFLAGS += -O3
# CFLAGS += -O3


# "Fixes" warning about old headers
CPPFLAGS += -Wno-deprecated

CPPFLAGS += -I$(top_srcdir)
CPPFLAGS += -I$(top_srcdir)/util
CPPFLAGS += $(BOOST_CPPFLAGS) @LOGGER_CFLAGS@ @LIBCONFIG_CFLAGS@ @LOG4CXX_CFLAGS@

# root of the watcher tree, one directory up from the srcdir
TOPDIR=$(top_srcdir)/..

LIBS += @LIBCONFIG_LIBS@
LIBS += @LOG4CXX_LIBS@
LIBS += @LIBYAML_LIBS@
LIBS += $(BOOST_ASIO_LIB) $(BOOST_THREAD_LIB) $(BOOST_SYSTEM_LIB) $(BOOST_FILESYSTEM_LIB) $(BOOST_REGEX_LIB)
LIBS += $(LOGGER_LIBS)

LDFLAGS += $(BOOST_LDFLAGS)

#
# Copy sample cfg and log.properties files from ../etc
#
%.cfg : 
	@ echo Creating $*.cfg from sample configuration at $(TOPDIR)/etc/$*.cfg.sample
	cp -v $(TOPDIR)/etc/$*.cfg.sample ./$*.cfg

%.log.properties: 
	@ echo Creating $*.log.properties from sample configuration at $(TOPDIR)/etc/watcher.log.properties.sample
	cp -v $(TOPDIR)/etc/watcherd.log.properties.sample ./$*.log.properties
	@ echo This is probably a bad idea - attempting to set the correct output log file in log.properties.
	@ perl -pi -e 's/watcherd.log/$*.log/g' ./$*.log.properties

ctags:
	ctags -R $(TOPDIR)

