#!/bin/sh
#
# $Id: runolsrd,v 1.3 2006/11/13 16:06:35 tjohnson Exp $
#
# Script to run hslsd from data in a simulator config file
# intended to be called by runcoke

PATH=$PATH:/sbin:/usr/sbin
export PATH

CONFFILE=$1

TAG=234635

if test x$CONFFILE = x
then
echo "usage: runolsrd configfile"
exit
fi

./labeltest -g $TAG -n 0 -r gn

manetnetwork=`awk ' BEGIN {FS=":"} $1=="manetnetwork" {  split($2,addr,"[:.]") ; print addr[1] "." addr[2] "." addr[3]  } ' $CONFFILE `

tmp=`/sbin/ifconfig -a | awk ' $2=="Link" { interface= $1 } $1=="inet" { if (index($2,"'$manetnetwork'")==6) print interface " " $2 } '`

interface=`echo $tmp | awk ' { print $1 } ' `
addr=`echo $tmp | awk ' { print $2 } ' | awk ' BEGIN { FS=":" } { print $2 } ' `

echo "manet $manetnetwork interface $interface addr $addr"
echo

# Nuke any existing routes...
#netstat -rn | awk ' $1 ~ /'$manetnetwork'.*/ { print "/sbin/route del -host " $1 " gw " $2  } ' | sh
ip route flush scope global type unicast;

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 > /proc/sys/net/ipv4/conf/$interface/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/$interface/accept_redirects
echo 0 > /proc/sys/net/ipv4/conf/default/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/default/accept_redirects
echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects

#/sbin/route add -net 224.0.0.0/4 dev $interface

ulimit -c unlimited


cat <<EOF  > /var/tmp/olsrd.conf
DebugLevel	1
IpVersion	4
AllowNoInt	yes

# TOS(type of service) value for
# the IP header of control traffic.
# If not set it will default to 16

#TosValue	16

IpcConnect
{
     MaxConnections  0
     Host            127.0.0.1
     Host            192.168.1.1
}
UseHysteresis	yes

# Polling rate in seconds(float). 
# Default value 0.05 sec

Pollrate	0.05

Interface "$interface"
{
    # IPv4 broadcast address to use. The
    # one usefull example would be 255.255.255.255
    # If not defined the broadcastaddress
    # every card is configured with is used

    # Ip4Broadcast		255.255.255.255

    # IPv6 address scope to use.
    # Must be 'site-local' or 'global'

    # Ip6AddrType		site-local

    # IPv6 multicast address to use when
    # using site-local addresses.
    # If not defined, ff05::15 is used

    # Ip6MulticastSite		ff05::11

    # IPv6 multicast address to use when
    # using global addresses
    # If not defined, ff0e::1 is used

    # Ip6MulticastGlobal	ff0e::1


    # Emission intervals.
    # If not defined, RFC proposed values will
    # be used in most cases.

    # Hello interval in seconds(float)
    # HelloInterval    2.0

    # HELLO validity time
    # HelloValidityTime	6.0

    # TC interval in seconds(float)
    # TcInterval        5.0

    # TC validity time
    # TcValidityTime	15.0

    # MID interval in seconds(float)
    # MidInterval	5.0

    # MID validity time
    # MidValidityTime	15.0

    # HNA interval in seconds(float)
    # HnaInterval	5.0

    # HNA validity time
    # HnaValidityTime 	15.0
}
EOF

/usr/home/tjohnson/olsrd-0.4.8/olsrd -f /var/tmp/olsrd.conf

./labeltest -n 0 -g $TAG -b 255.0.0.255 -f 255.255.255.255 -l "olsrd crashed"
