#!/bin/sh

# smooths the incoming data by doing the sliding window thing
#
#  arg $1 is the size of the window.
#
#  reads $1 rows (to fill the window), and then generates a row for every row.
#
# $Id: smooth,v 1.1 2005/01/21 20:59:50 tjohnson Exp $
#

awk ' BEGIN { line=0} { window[line] = $1; line++ ; count++; }  count > '$1' { avg=0; for(i=0;i<'$1';i++) avg+=window[i]; print avg/'$1' ; if (line>='$1') line=0; } '
